"""
Django settings for FINALYEARPROJECT project.

Generated by 'django-admin startproject' using Django 4.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from datetime import timedelta

BASE_DIR = Path(__file__).resolve().parent.parent
_env_path = BASE_DIR / '.env'

# Load environment variables from .env file
if _env_path.exists():
    load_dotenv(dotenv_path=str(_env_path), override=True)
    print(f"✅ Loaded .env from: {_env_path}")
else:
    print(f"⚠️  .env file not found at: {_env_path}")
    load_dotenv()  # Fallback to default locations


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# Debug: Verify environment variables are loaded
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')
CLAUDE_API_KEY = os.environ.get('CLAUDE_API_KEY')

print(f"🔑 Environment Variables Debug:")
print(f"   - GEMINI_API_KEY: {'Found' if GEMINI_API_KEY else 'Missing'}")
print(f"   - CLAUDE_API_KEY: {'Found' if CLAUDE_API_KEY else 'Missing'}")
if GEMINI_API_KEY:
    print(f"   - Gemini Key Length: {len(GEMINI_API_KEY)} characters")
    print(f"   - Gemini Key Preview: {GEMINI_API_KEY[:10]}...{GEMINI_API_KEY[-4:]}")
if CLAUDE_API_KEY:
    print(f"   - Claude Key Length: {len(CLAUDE_API_KEY)} characters")
    print(f"   - Claude Key Preview: {CLAUDE_API_KEY[:10]}...{CLAUDE_API_KEY[-4:]}")

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'PARSON_PROBLEM_GENERATOR',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'FINALYEARPROJECT.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'FINALYEARPROJECT.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'django.contrib.staticfiles.finders.FileSystemFinder',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'PARSON_PROBLEM_GENERATOR.User'

JWT_ALGORITHM = 'HS256'


# CORS Handlers

CORS_ALLOW_HEADERS = ['*']

CORS_ALLOW_ALL_ORIGINS = True

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:3001",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:3001",
]

CORS_ORIGIN_WHITELIST = ['http://localhost:3000']
CORS_TRUSTED_ORIGINS = ['http://localhost:3000']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}



AUTHENTICATION_BACKENDS = [
    'PARSON_PROBLEM_GENERATOR.backends.CustomUserAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

SIGNING_KEY = os.environ.get('SIGNING_KEY')

# Optional: set ADMIN_CREATION_SECRET in .env to enable the /csu/ endpoint for creating admin accounts.
# If unset, the endpoint returns 403. Prefer Django shell for admin creation (see docs).
ADMIN_CREATION_SECRET = os.environ.get('ADMIN_CREATION_SECRET')

# Note: GEMINI_API_KEY and OPENAI_API_KEY are already defined above with debug logging
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-4o-mini')

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7), 
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30), 
    'AUTH_HEADER_TYPES': ('Bearer',),
    'SIGNING_KEY': SIGNING_KEY,
}

# Logging configuration for debugging AI integration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': 'debug.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'PARSON_PROBLEM_GENERATOR.services': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
    },
} 


